### ISSUE TITLE
It does not work on v3.6.0

### ISSUE THREAD

**Issue by fofwisdom** [DetLFY/ctfd-one-answer-challenge-plugin#1]
After adding the plugin, building, and restarting, I only get a white screen in the Create Challenge menu.

**Comment by DetLFY** [comment]
Thanks for your issue,  I'm sorry that I just only test the plugin in v3.4.0. Maybe it has some changes in later version of CTFd causing the plugin could not work normally. And before discussing that, could your tell me if you change the name of folder? It must be named "ctfd-one-answer-challenge-plugin".

**Comment by fofwisdom** [comment]
Oops, I renamed the folder without opening the script, I'll retest and close it myself if it's okay.

Thanks so much for the feedback!
